# Generated by Django 2.1.10 on 2019-11-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=250, null=True, verbose_name='DNI')),
                ('first_surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('last_surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Materno')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombres')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('ubigeo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ubigeo Code')),
                ('ubigeo_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ubigeo Name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=30, null=True)),
                ('status_civil', models.CharField(blank=True, max_length=250, null=True, verbose_name='Estado Civil')),
                ('mother_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Madre')),
                ('father_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Padre')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
