# Generated by Django 2.1.10 on 2019-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='year',
        ),
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ubigeo',
            field=models.PositiveIntegerField(blank=True, max_length=6, null=True, verbose_name='Ubigeo Code'),
        ),
    ]
